import type { Project, BlogPost, Testimonial, Skill, Service, ExperienceItem } from './types'

export const projects: Project[] = [
  {
    id: '1',
    title: 'SaaS Analytics Dashboard',
    description: 'A full-featured analytics dashboard with real-time data visualization, user management, and subscription billing integration.',
    image: '/projects/dashboard.jpg',
    tech: ['Next.js', 'TypeScript', 'Supabase', 'Tailwind CSS', 'Chart.js'],
    category: 'Web',
    live_url: '#',
    github_url: '#',
    featured: true,
    created_at: '2024-12-01',
  },
  {
    id: '2',
    title: 'E-Commerce Mobile App',
    description: 'Cross-platform mobile app with smooth product browsing, cart management, and secure payment processing.',
    image: '/projects/ecommerce.jpg',
    tech: ['React Native', 'Expo', 'Supabase', 'Stripe'],
    category: 'Mobile',
    live_url: '#',
    github_url: '#',
    featured: true,
    created_at: '2024-10-15',
  },
  {
    id: '3',
    title: 'AI Content Generator',
    description: 'An intelligent content generation platform powered by AI with custom prompt templates and bulk export.',
    image: '/projects/ai-content.jpg',
    tech: ['Next.js', 'OpenAI API', 'Tailwind CSS', 'Supabase'],
    category: 'AI',
    live_url: '#',
    github_url: '#',
    featured: true,
    created_at: '2024-09-01',
  },
  {
    id: '4',
    title: 'Real Estate Platform',
    description: 'Property listing and management platform with advanced search filters, map integration, and agent portal.',
    image: '/projects/realestate.jpg',
    tech: ['Next.js', 'TypeScript', 'PostgreSQL', 'Google Maps API'],
    category: 'Business',
    live_url: '#',
    github_url: '#',
    featured: false,
    created_at: '2024-08-01',
  },
  {
    id: '5',
    title: 'Fitness Tracking App',
    description: 'Mobile fitness app with workout plans, progress tracking, nutrition logging, and social features.',
    image: '/projects/fitness.jpg',
    tech: ['React Native', 'Expo', 'Firebase', 'Redux'],
    category: 'Mobile',
    live_url: '#',
    github_url: '#',
    featured: false,
    created_at: '2024-07-01',
  },
  {
    id: '6',
    title: 'AI Chatbot Platform',
    description: 'Enterprise chatbot solution with custom training, multi-language support, and seamless CRM integration.',
    image: '/projects/chatbot.jpg',
    tech: ['Next.js', 'LangChain', 'OpenAI', 'Supabase', 'TypeScript'],
    category: 'AI',
    live_url: '#',
    github_url: '#',
    featured: false,
    created_at: '2024-06-01',
  },
]

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Building Scalable React Applications with Next.js 15',
    slug: 'building-scalable-react-applications-nextjs-15',
    thumbnail: '/blog/nextjs.jpg',
    category: 'Next.js',
    read_time: 8,
    excerpt: 'Explore the latest features in Next.js 15 and how to leverage them for building production-ready applications.',
    content: '',
    published_at: '2024-12-10',
    created_at: '2024-12-10',
  },
  {
    id: '2',
    title: 'Mastering Tailwind CSS: Advanced Patterns and Best Practices',
    slug: 'mastering-tailwind-css-advanced-patterns',
    thumbnail: '/blog/tailwind.jpg',
    category: 'CSS',
    read_time: 6,
    excerpt: 'Deep dive into advanced Tailwind CSS techniques that will elevate your UI development workflow.',
    content: '',
    published_at: '2024-11-25',
    created_at: '2024-11-25',
  },
  {
    id: '3',
    title: 'AI Prompt Engineering: A Developer\'s Guide',
    slug: 'ai-prompt-engineering-developers-guide',
    thumbnail: '/blog/ai.jpg',
    category: 'AI',
    read_time: 10,
    excerpt: 'Learn the art of crafting effective prompts to get the best results from AI language models in your projects.',
    content: '',
    published_at: '2024-11-10',
    created_at: '2024-11-10',
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    role: 'Product Manager',
    company: 'TechVentures Inc.',
    feedback: 'Amir delivered an exceptional SaaS dashboard that exceeded our expectations. His attention to detail and commitment to performance optimization resulted in a 40% improvement in our app\'s load time.',
    rating: 5,
    created_at: '2024-11-01',
  },
  {
    id: '2',
    name: 'Michael Chen',
    role: 'CTO',
    company: 'StartupHub',
    feedback: 'Working with Amir was a fantastic experience. He transformed our Figma designs into pixel-perfect, responsive interfaces with seamless animations. Highly recommended for any frontend work.',
    rating: 5,
    created_at: '2024-10-15',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    role: 'Founder',
    company: 'MobileFirst Agency',
    feedback: 'Amir built our React Native app from scratch and delivered a polished, performant product on time. His expertise in mobile development and UI/UX is truly impressive.',
    rating: 5,
    created_at: '2024-09-20',
  },
]

export const skills: Record<string, Skill[]> = {
  Frontend: [
    { name: 'React', category: 'Frontend' },
    { name: 'Next.js', category: 'Frontend' },
    { name: 'JavaScript', category: 'Frontend' },
    { name: 'TypeScript', category: 'Frontend' },
    { name: 'Tailwind CSS', category: 'Frontend' },
    { name: 'Framer Motion', category: 'Frontend' },
    { name: 'HTML5 / CSS3', category: 'Frontend' },
    { name: 'Redux', category: 'Frontend' },
  ],
  Mobile: [
    { name: 'React Native', category: 'Mobile' },
    { name: 'Expo', category: 'Mobile' },
    { name: 'iOS / Android', category: 'Mobile' },
  ],
  Backend: [
    { name: 'Supabase', category: 'Backend' },
    { name: 'Firebase', category: 'Backend' },
    { name: 'MySQL', category: 'Backend' },
    { name: 'REST APIs', category: 'Backend' },
    { name: 'Node.js', category: 'Backend' },
  ],
  Tools: [
    { name: 'Git / GitHub', category: 'Tools' },
    { name: 'Figma', category: 'Tools' },
    { name: 'VS Code', category: 'Tools' },
    { name: 'Vercel', category: 'Tools' },
  ],
  AI: [
    { name: 'Prompt Engineering', category: 'AI' },
    { name: 'AI Workflows', category: 'AI' },
    { name: 'OpenAI API', category: 'AI' },
    { name: 'LangChain', category: 'AI' },
  ],
}

export const services: Service[] = [
  {
    title: 'Web Development',
    description: 'Building fast, scalable, and SEO-optimized web applications using modern technologies like Next.js, React, and TypeScript.',
    icon: 'Globe',
    features: ['Next.js / React', 'TypeScript', 'REST & GraphQL APIs', 'Performance Optimization'],
  },
  {
    title: 'Mobile App Development',
    description: 'Creating cross-platform mobile applications with React Native and Expo that deliver native-like performance.',
    icon: 'Smartphone',
    features: ['React Native', 'iOS & Android', 'Expo Framework', 'App Store Deployment'],
  },
  {
    title: 'UI/UX Implementation',
    description: 'Converting Figma designs into pixel-perfect, responsive interfaces with smooth animations and micro-interactions.',
    icon: 'Palette',
    features: ['Figma to Code', 'Responsive Design', 'Framer Motion', 'Shadcn UI / Tailwind'],
  },
  {
    title: 'SEO Optimization',
    description: 'Implementing technical SEO best practices to boost search rankings and organic traffic for your web applications.',
    icon: 'TrendingUp',
    features: ['Technical SEO', 'Core Web Vitals', 'Schema Markup', 'Performance Audit'],
  },
  {
    title: 'AI Solutions',
    description: 'Integrating AI capabilities into your products — from chatbots to content generation and intelligent automation.',
    icon: 'Cpu',
    features: ['OpenAI Integration', 'AI Chatbots', 'Prompt Engineering', 'LangChain Workflows'],
  },
]

export const experience: ExperienceItem[] = [
  {
    title: 'Senior Frontend Engineer',
    company: 'Freelance / Remote',
    period: '2022 – Present',
    description: 'Delivering high-quality web and mobile solutions for clients worldwide. Specializing in React, Next.js, and React Native with a focus on performance and user experience.',
    type: 'freelance',
  },
  {
    title: 'Frontend Developer',
    company: 'TechSolutions Ltd.',
    period: '2020 – 2022',
    description: 'Led frontend development for multiple SaaS products, implemented design systems, and mentored junior developers. Reduced page load times by 35% through optimization strategies.',
    type: 'work',
  },
  {
    title: 'React Developer',
    company: 'Digital Agency Co.',
    period: '2019 – 2020',
    description: 'Built responsive web applications and converted Figma designs to production code. Worked closely with designers and backend teams using Agile methodology.',
    type: 'work',
  },
  {
    title: 'Open Source Contributor',
    company: 'Personal Projects',
    period: '2018 – Present',
    description: 'Developed and maintained open-source tools and templates used by hundreds of developers. Active contributor to the React and Next.js community.',
    type: 'project',
  },
]

export const stats = [
  { value: '5+', label: 'Years Experience' },
  { value: '50+', label: 'Projects Completed' },
  { value: '30+', label: 'Happy Clients' },
  { value: '15+', label: 'Technologies' },
]
